{% set name = "elara" %}
{% set version = "0.5.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/elara-{{ version }}.tar.gz
  sha256: 2758e9245cad36126330797aee70744f52d77dc5ce50f16ea231519d34741f8a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cryptography
    - msgpack-python
    - python >={{ python_min }}
    - safer

test:
  imports:
    - elara
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/saurabh0719/elara
  summary: Elara DB is an easy to use, lightweight NoSQL database.
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Elara DB is a NoSQL database written for python that can also be used as a
     fast in-memory cache for JSON-serializable data. It includes various
     methods and features to manipulate data structures in-memory, to protect
     database files, and also to export data.

extra:
  recipe-maintainers:
    - thewchan
